<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/localhost" />
    <meta charset="UTF-8" />
    <title><?= $pageTitle ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keyWords ?>" />
    <link rel="stylesheet" href="static/css/stylesheet.css" type="text/css"/>
</head>

<body>
    <header>
        <h1>Welcome to BETS portal.</h1>
    </header>

    <nav>
        <ul>
            <li><a href="">nav1</a></li>
            <li><a href="">nav2</a></li>
            <li><a href="">nav3</a></li>
        </ul>
    </nav>
    <br clear="both" />

    <h2>Obsah tela</h2>
    <?= $this->controller->renderView(); ?>

    <footer>
        <h2>This is footer!</h2>
    </footer>

</body>
</html>