<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/localhost:8080/bets/" />
    <meta charset="UTF-8" />
    <title><?= $pageTitle ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keyWords ?>" />
<!--    <link rel="stylesheet" href="./../static/css/stylesheet.css" type="text/css"/>-->
    <link rel="stylesheet" href="style.css" type="text/css"/>
    <script type="text/javascript" src="static/js/script.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>

<body>
    <fieldset>
        <legend>Hlavicka</legend>
        <header>
            <h1>Bets portal.</h1>
        </header>
        <nav>
            <ul>
                <li><a href="/bets">nav1</a></li>
                <li><a href="/bets">nav2</a></li>
                <li><a href="/bets">nav3</a></li>
            </ul>
        </nav>

        <input type="email" name="loginEmail" placeholder="Email">
        <input type="password" name="loginPassword" placeholder="Password">
        <button id="loginButton">Log in</button>
    </fieldset>

    <br clear="both" />

    <fieldset>
        <legend>Obsah tela</legend>
        <?= $this->controller->renderView(); ?>
    </fieldset>

    <br clear="both" />

    <fieldset>
        <legend>Paticka</legend>
        <footer>
            <h2>This is footer!</h2>
        </footer>
    </fieldset>

</body>
</html>